elo nic nie działa
Hubert2113/WeatherApp pull request #3
Opened 2022-04-14 11:35 UTC by MartaCzerniak

robię pull requesta to może ktoś zobaczy czemu nie gra css

2022-04-14 11:59 UTC, michal-wolski requested changes
Dodaj .scss do każdego

2022-04-14 18:41 UTC, dmjs23 commented
teraz na szybko przeglądając to dodaj do html
<link rel="stylesheet" href="./sass/main.css" />
ale nie wgłębiłem się jeszcze w to co napisałaś

2022-04-14 21:59 UTC, dmjs23 requested changes
w scss linijka od padding nie moze mieć przecinków
padding: 0px, 12px, 0px, 12px;

w common sciazke daj
background-image: url('../images/bg-desktop.jpg');
i usuń
repeat
bo to powoduje błąd 

repeat jest z domysłu na yes jak chcesz je wyłączyć to daj
backgraund-repeat: no;

2022-04-14 22:19 UTC, dmjs23 commented on src/sass/index/_common.scss
> +    background-image: url("/src/images/bg-desktop.jpg") repeat;
background-image: url("../images/bg-desktop.jpg");

2022-04-14 22:20 UTC, dmjs23 commented on src/sass/utilities/_buttons.scss
> +    padding: 0px, 12px, 0px, 12px;
padding: 0px 12px 0px 12px;

2022-04-14 22:23 UTC, dmjs23 requested changes

2022-04-14 22:23 UTC, dmjs23 commented on src/sass/index/_common.scss
> +    background-image: url("/src/images/bg-desktop.jpg") repeat;
background-image: url("../images/bg-desktop.jpg") ;

2022-04-14 22:23 UTC, dmjs23 commented on src/sass/utilities/_buttons.scss
> +    padding: 0px, 12px, 0px, 12px;
padding: 0px 12px 0px 12px;

2022-04-18 20:30 UTC, Hubert2113 requested changes
brak przycisku wysyłania danych w formularzu, reszta jest ok

2022-04-19 14:48 UTC, dmjs23 commented on src/index.html
> +        </form>
brakuje przycisku submit

2022-04-19 19:37 UTC, Hubert2113 approved these changes

2022-04-19 20:03 UTC, dmjs23 reviewed
ok, tylko rozwiazac konflikty trzeba

2022-04-19 20:03 UTC, dmjs23 approved these changes

2022-04-19 22:00 UTC, merged